module.exports = {
  root: true,
  parser: '@typescript-eslint/parser',
  parserOptions: {
    ecmaVersion: 'latest',
    sourceType: 'module',
    ecmaFeatures: {
      jsx: true,
    },
  },
  plugins: ['sonarjs'],
  extends: ['react-app', 'turbo', 'plugin:sonarjs/recommended', 'prettier'],
  rules: {
    'array-bracket-spacing': 0,
    'arrow-parens': 0,
    'arrow-spacing': 0,
    'block-spacing': 0,
    'comma-dangle': 0,
    'jsx-quotes': 0,
    'key-spacing': 0,
    'keyword-spacing': 0,
    'no-multiple-empty-lines': 0,
    'no-console': [
      1,
      {
        allow: ['info', 'error'],
      },
    ],
    'no-trailing-spaces': 0,
    'object-curly-spacing': 0,
    'prefer-const': 1,
    quotes: 0,
    semi: 0,
    'space-before-blocks': 0,
    'space-before-function-paren': 0,
    'space-in-parens': 0,
    'space-infix-ops': 0,
    'comma-spacing': 0,
    'eol-last': 0,
    'import/namespace': 0,
    'import/no-anonymous-default-export': 0,
    'import/no-unresolved': 0,
    'import/named': 0,
    'import/order': 0,
    'jsx-a11y/anchor-is-valid': 0,
    'react/jsx-tag-spacing': 0,
    'react/jsx-pascal-case': 0,
    'react/self-closing-comp': 0,
    'react-hooks/exhaustive-deps': 0,
    '@typescript-eslint/explicit-module-boundary-types': 0,
    '@typescript-eslint/semi': 0,
    '@typescript-eslint/indent': 0,
    '@typescript-eslint/ban-ts-ignore': 0,
    '@typescript-eslint/ban-ts-comment': 0,
    '@typescript-eslint/explicit-function-return-type': 0,
    '@typescript-eslint/explicit-member-accessibility': 0,
    '@typescript-eslint/no-empty-interface': 0,
    '@typescript-eslint/prefer-interface': 0,
    '@typescript-eslint/no-use-before-define': 0,
    '@typescript-eslint/no-object-literal-type-assertion': 0,
    '@typescript-eslint/no-parameter-properties': 0,
    '@typescript-eslint/no-non-null-assertion': 0,
    '@typescript-eslint/camelcase': 0,
    '@typescript-eslint/no-redeclare': 0,
    '@typescript-eslint/type-annotation-spacing': 0,
    '@typescript-eslint/object-curly-spacing': 0,
    'sonarjs/prefer-immediate-return': 0,
  },
  ignorePatterns: ['**/dist/**/*.js', '**/node_modules/**/*.{js,ts,tsx}'],
};
